name: Publish 1.7

on:
  push:
    branches:
      - "dev/1.7"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/actions/wrapper-validation@v3
      - run: cd test-mod && ./gradlew
      - run: ./gradlew build publish --stacktrace
        env:
          MAVEN_PUBLISH_CREDENTIALS: ${{ secrets.MAVEN_PUBLISH_CREDENTIALS }}
